### ISSUE TITLE
2.0 Feature Documentation

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Handbook#294]
As per @mhegazy's email:
- [x] `null` (https://github.com/Microsoft/TypeScript-Handbook/issues/313)
- [x] `undefined` (https://github.com/Microsoft/TypeScript-Handbook/issues/313)
- [x] `never` (https://github.com/Microsoft/TypeScript-Handbook/issues/313)
- [x] strictNullChecks section (https://github.com/Microsoft/TypeScript-Handbook/issues/313)
- [x] UMD (https://github.com/Microsoft/TypeScript-Handbook/issues/309)
- [x] readonly properties and index signatures (https://github.com/Microsoft/TypeScript-Handbook/issues/311)
- [x] `this` in functions (https://github.com/Microsoft/TypeScript-Handbook/issues/310)
- [x] Shorthand ambient module declarations and wildcard matching in module names (https://github.com/Microsoft/TypeScript-Handbook/issues/308)
- [x] new compiler options
- [x] `--lib` (#291)
- [x] Discriminated union types (https://github.com/Microsoft/TypeScript-Handbook/issues/312)
- [x] glob support (https://github.com/Microsoft/TypeScript-Handbook/issues/324)
- [x] `--noUnusedVariables` and `--noUnusedParameters`
- [x] `/// <reference types=".." />` documentation (https://github.com/Microsoft/TypeScript-Handbook/issues/348)
- [x] Refresh the playground

**Comment by yuit** [comment]
Add following flags into Compiler Options pages:
- [ ] `--disableProjectSizeLimit`

- [ ] `--noUnusedLocals`

- [ ] ` --noUnusedParameters`

Add following into tsconfig pages:

- [ ] typesSearchPaths

- [ ] typeRoots

- [ ] types
